export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  ATTENDENCE_SNAPSHOTS: "ATTENDENCE_SNAPSHOTS",
  EMLOYEE_SNAPSHOT: "EMLOYEE_SNAPSHOT",
  ATTENDENCE_CHANGE: "ATTENDENCE_CHANGE"
};
